### ISSUE TITLE
Error on GP inference

### ISSUE THREAD

**Issue by BugsBuggy** [aryandeshwal/HyBO#1]
Hello together,
Sometimes I get an error when running HyBO for some iterations (<100) that is thrown in this function:
https://github.com/aryandeshwal/HyBO/blob/3298db751b4d6e9a445d104de5c634e4af4a8dfe/GPmodel/inference/inference.py#L29

The error is as follows:
`raise RuntimeError('Absolute entry values of Gram matrix are between %.4E~%.4E with trace %.4E' %
RuntimeError: Absolute entry values of Gram matrix are between 1.4760E-03~5.4342E-02 with trace 4.4024E+00`

I'm running 90 trials out of which 10 are random trials.
Any ideas what is happening exactly and how to fix it?

**Comment by aryandeshwal** [comment]
Hello, this error occurs in cholesky decomposition of the kernel matrix when it becomes ill-conditioned. This is a common error with gaussian process models. I can suggest few general things for identifying/fixing the causes:
1. See if there are similar input points in the evaluated trials over iterations. A simple fix is to discard input points if they are similar to the already evaluated set. 
2. The ill-conditioning can also be improved by adding a jitter to the matrix diagonal before computing the cholesky decomposition. However, we've set the jitter to go up to 1e-3 which is already pretty high. Adding higher jitter values will decrease the influence of training data. 

Please try [1] first and see if it solves the issue and please let me know if it doesn't.

**Comment by BugsBuggy** [comment]
Thanks for the quick reply,
The problem is that my hyperparameter space contains more than 20 mixed-type variables. It's not obvious which are similar to the already evaluated set.

**Comment by aryandeshwal** [comment]
one simple way is to check the euclidean distance between the variables.

**Comment by BugsBuggy** [comment]
Okay, this would mean I would have to find out empirically how similar they can be to determine a threshold to discard inputs, I guess. You can close the issue if this is indeed the case, thank you :)

**Comment by aryandeshwal** [comment]
Yes, close points can lead to kernel ill-conditioning sometimes. Hopefully it will fix the issue for you. Thank you!
