### ISSUE TITLE
Minimum number of initialization trials

### ISSUE THREAD

**Issue by BugsBuggy** [aryandeshwal/HyBO#2]
Hello together,
I want to test the optimization behaviour in a setting where the number of random initialization trials is as low as possible. However, running approx. 0-2 initialization trials results in the following error in this line:

https://github.com/aryandeshwal/HyBO/blob/3298db751b4d6e9a445d104de5c634e4af4a8dfe/GPmodel/sampler/priors.py#L31

![image](https://user-images.githubusercontent.com/14214757/153557215-f4421f3b-4066-47dc-8d62-576afa237e26.png)

How low can we set the number of suggested initialization trials?
Is there a good range that will not crash?

Thanks in advance

**Comment by aryandeshwal** [comment]
Hi, ideally even two points should work if the output values for those two evaluations are not same. ``stable_dev`` is defined as the difference between ``output_max-output_min`` (line 23 and 30). Please check the output values you are getting and why ``stable_dev`` is becoming zero.

**Comment by BugsBuggy** [comment]
Thanks, this clarified the issue!
